VERSION="2.20.0"                                                    
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 

[DOCUMENTATION] 
ORG_NAME="SUBS Token" 
ORG_URL="https://subs.toml.host" 
ORG_LOGO="https://subs.toml.host/logo.png" 

[[CURRENCIES]] 
code="SUBS" 
issuer="GD6K4SSFOHK7HZWMENMEZZX5SBMMIQI6FFJSIAGKMENGLBVBXK6KSUBS" 
status="live" 
name="Subscriber Token" 
desc="Subscribers Token (Asset Code : SUBS) is rewarding token for social media followers and strengthen audience of the community members." 
display_decimals=7 
conditions="Buy SUBS Token to give rewards for your social media followers and strengthen audience of your own community." 
image="https://subs.toml.host/logo.png" 
